### ISSUE TITLE
Lastfm Scrobbler not working properly

### ISSUE THREAD

**Issue by touminn** [iMyon/OsuLastfmScrobbler#1]
On Stable 20211028.2, cmd outputs "System.NullReferenceException: Object reference not set to an instance of an object.", as well as "System.IO.FileNotFoundException" (which generates infinitely). This happens every time a map is played, logfile below

[Log-2021-10-31@02.01.35.txt](https://github.com/iMyon/OsuLastfmScrobbler/files/7448200/Log-2021-10-31%4002.01.35.txt)

**Comment by iMyon** [comment]
try [this](https://github.com/iMyon/OsuLastfmScrobbler/releases/tag/0.0.2).

**Comment by touminn** [comment]
OsuRTDataProvider might be outdated as of Stable 20220406.3, outputting:
`[OsuRTDataProviderPlugin]System.NullReferenceException: Object reference not set to an instance of an object.
   at OsuLastfmScrobbler.client.OsuScrobbler.<HandleListenerEvents>b__15_1(Int32 ms)
   at OsuRTDataProvider.Listen.OsuListenerManager.ListenLoopUpdate()`

included log file again below. thank you for your help
[Log-2022-04-06@04.28.14.txt](https://github.com/iMyon/OsuLastfmScrobbler/files/8430348/Log-2022-04-06%4004.28.14.txt)

**Comment by iMyon** [comment]
Yes, won't be fixed until OsuRTDataProvider updates.

**Comment by touminn** [comment]
understood. thank you

**Comment by iMyon** [comment]
fixed. [0.0.3](https://github.com/iMyon/OsuLastfmScrobbler/releases/tag/0.0.3)

**Comment by touminn** [comment]
i love you
