### ISSUE TITLE
Lastfm verify error

### ISSUE THREAD

**Issue by aleteklas** [iMyon/OsuLastfmScrobbler#2]
I filled Apikey, Apisecret, username and password, but it still doesn't verify

**Comment by iMyon** [comment]
This program is not working properly now, see #1

**Comment by iMyon** [comment]
download [0.0.3](https://github.com/iMyon/OsuLastfmScrobbler/releases/tag/0.0.3) and retry.

**Comment by aleteklas** [comment]
It works, but only with VPN on, but I guess it's lastfm's problem
